* Design
  1. I installed Qt.
  2. Juan Carbajal, juancarbajal98@gmail.com
  3. Project Approximania
     - Details
       Application will take a function to be plotted, and user will guess a max on that function. If user is within error bound, they get to play a game where a character will ride on the curve of the function.
     - Design
       There will be a title screen with a text box to take in a function to be plotted. The plot will appear and user can make a guess of an extremum within the bound of the plot. If it is within the bound, they play, if not they get more tries depending on difficulty.
     - Plan
       - Week 3: Title Screen, lower level approximation method
       - Week 4: Plotting the Function correctly
       - Week 5: implementing user interface with the curve
       - Week 6: implementing user interface with the curve
       - Week 7: cleaning up GUI
       - Week 8: polishing code and GUI
* Draft
  - function class
    - constants
    - power
    - max/mins
    - bounds
  - plotter
  - graph
  - linerider
